const detail =[
  {
    "id":"0001",
    "banner":"/static/images/tuijian.jpg",
    "title":"推荐专区分类",
    "productList":[
      {
        "thumb":"/static/images/tuijian_icon.png",
        "name":"街舞01"
      },
      {
        "thumb":"/static/images/tuijian_icon.png",
        "name":"芭蕾舞02"
      },
      {
        "thumb":"/static/images/tuijian_icon.png",
        "name":"现代舞01"
      },
      {
        "thumb":"/static/images/tuijian_icon.png",
        "name":"国标舞04"
      }
    ]
  },
  {
    "id":"0002",
    "banner":"/static/images/xiaji.jpg",
    "title":"街舞专区",
    "productList":[
      {
        "thumb":"/static/images/xiaji_icon.png",
        "name":"街舞01"
      },
      {
        "thumb":"/static/images/xiaji_icon.png",
        "name":"街舞02"
      },
      {
        "thumb":"/static/images/xiaji_icon.png",
        "name":"街舞03"
      },
      {
        "thumb":"/static/images/xiaji_icon.png",
        "name":"街舞04"
      },
      {
        "thumb":"/static/images/xiaji_icon.png",
        "name":"街舞05"
      },
      {
        "thumb":"/static/images/xiaji_icon.png",
        "name":"街舞01"
      },
      {
        "thumb":"/static/images/xiaji_icon.png",
        "name":"街舞06"
      },
      {
        "thumb":"/static/images/xiaji_icon.png",
        "name":"街舞07"
      }
    ]
  },
  {
    "id":"0003",
    "banner":"/static/images/gexing.jpg",
    "title":"芭蕾舞专区",
    "productList":[
      {
        "thumb":"/static/images/gexing_icon.png",
        "name":"芭蕾舞01"
      },
      {
        "thumb":"/static/images/gexing_icon.png",
        "name":"芭蕾舞02"
      },
      {
        "thumb":"/static/images/gexing_icon.png",
        "name":"芭蕾舞03"
      },
      {
        "thumb":"/static/images/gexing_icon.png",
        "name":"芭蕾舞04"
      },
      {
        "thumb":"/static/images/gexing_icon.png",
        "name":"芭蕾舞05"
      },
      {
        "thumb":"/static/images/gexing_icon.png",
        "name":"芭蕾舞06"
      },

    ]
  },
  {
    "id":"0004",
    "banner":"/static/images/jujia.jpg",
    "title":"现代舞专区",
    "productList":[
      {
        "thumb":"/static/images/jujia_icon.png",
        "name":"现代舞01"
      },
      {
        "thumb":"/static/images/jujia_icon.png",
        "name":"现代舞01"
      },
      {
        "thumb":"/static/images/jujia_icon.png",
        "name":"现代舞01"
      },
      {
        "thumb":"/static/images/jujia_icon.png",
        "name":"现代舞01"
      },
      {
        "thumb":"/static/images/jujia_icon.png",
        "name":"现代舞01"
      },

    ]
  },
  {
    "id":"0005",
    "banner":"/static/images/peijian.jpg",
    "title":"国标舞专区",
    "productList":[
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      },
      {
        "thumb":"/static/images/peijian_icon.png",
        "name":"国标舞01"
      }
    ]
  },
]

export default detail
